weather_data_models:
  outputs:
    dev:
      type: duckdb
      # mapping to mounted volume of duckdb.
      path: /opt/airflow/dags/weather_data.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
